version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db

  ui:
    image: konvio/angular-agency-ui
    ports:
      - "4200:80"
    profiles:
      - prod
    depends_on:
      - api

  api:
    image: konvio/kotlin-agency-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/db
    profiles:
      - prod
    depends_on:
      - mongo

  ui-dev:
    build:
      context: ./ui
      dockerfile: ./docker/.Dockerfile
    ports:
      - "4200:80"
    profiles:
      - dev
    depends_on:
      - api-dev

  api-dev:
    build:
      context: ./
      dockerfile: ./docker/.Dockerfile
    ports:
      - "8080:8080"
    hostname: api
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/db
    profiles:
      - dev
    depends_on:
      - mongo
