version: '3.9'

services:

  ui:
    image: konvio/angular-agency-ui
    network_mode: "host"
    depends_on:
      - api

  api:
    image: konvio/kotlin-agency-api
    network_mode: "host"
    depends_on:
      - mongo

  mongo:
    image: mongo
    network_mode: "host"
    volumes:
      - ./data/mongo:/data/db
